# Generated by Django 6.0.1 on 2026-02-08 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='paymentgatewayconfig',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_payment_gateway'),
        ),
        migrations.AddField(
            model_name='refund',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='orders.order'),
        ),
        migrations.AddField(
            model_name='refund',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='refund',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['gateway', 'created_at'], name='payments_tr_gateway_3c9d48_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlog',
            index=models.Index(fields=['transaction_type', 'created_at'], name='payments_tr_transac_f036c2_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_id'], name='payments_pa_payment_6c9e39_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='payments_pa_created_b8a300_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'created_at'], name='payments_pa_user_id_5bbfc5_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['refund_id'], name='payments_re_refund__b47155_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['status'], name='payments_re_status_715c3a_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['requested_at'], name='payments_re_request_708c7c_idx'),
        ),
    ]
